name: PlaytimeLimit
version: '${version}'
main: com.github.b1kku.playtimelimit.PlaytimeLimit
api-version: 1.18
authors: [ B1kku ]
description: Limits player playtime on a configurable manner.
website: github.com/b1kku
commands:
  resetTime:
    description: Resets the playtime of everyone.
  playTime:
    description: Adds playtime to someone.
    usage: /<command> [add/reduce] player seconds